# Generated by Django 6.1.1 on 2026-09-11 13:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(db_column='dep_id', primary_key=True, serialize=False)),
                ('dep_title', models.CharField(db_column='dep_title', max_length=100)),
                ('name_of_manager', models.CharField(db_column='name_of_manager', max_length=100, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(db_column='disease_id', primary_key=True, serialize=False)),
                ('disease_code', models.CharField(db_column='disease_code', unique=True)),
                ('disease_title', models.CharField(db_column='disease_title', max_length=100)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.AutoField(db_column='drug_id', primary_key=True, serialize=False)),
                ('drug_title', models.CharField(db_column='drug_title', max_length=100)),
                ('drug_type', models.CharField(db_column='drug_type', max_length=100)),
            ],
            options={
                'db_table': 'drug',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pres_id', models.AutoField(db_column='pres_id', primary_key=True, serialize=False)),
                ('recommendations', models.TextField(db_column='recommendations')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(db_column='room_id', primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(db_column='room_number', unique=True)),
                ('equipment', models.CharField(db_column='equipment', max_length=250, null=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('spec_id', models.AutoField(db_column='spec_id', primary_key=True, serialize=False)),
                ('spec_title', models.CharField(db_column='spec_title', max_length=100)),
            ],
            options={
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('REGISTRAR', 'Регистратор'), ('DOCTOR', 'Врач'), ('PATIENT', 'Пациент')], default='PATIENT', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(db_column='doctor_id', primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(db_column='doctor_name', max_length=100)),
                ('dep', models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.PROTECT, to='hospital_server_app.department')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.PROTECT, to='hospital_server_app.room')),
                ('spec', models.ForeignKey(db_column='spec_id', on_delete=django.db.models.deletion.PROTECT, to='hospital_server_app.specialization')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('card_number', models.AutoField(db_column='card_number', primary_key=True, serialize=False)),
                ('patient_name', models.CharField(db_column='patient_name', max_length=100)),
                ('birth_date', models.DateField(db_column='birth_date')),
                ('address', models.TextField(db_column='address', null=True)),
                ('insurance', models.CharField(db_column='insurance', max_length=16, null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='ReceptionLog',
            fields=[
                ('log_id', models.AutoField(db_column='log_id', primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(db_column='appointment_date')),
                ('status', models.CharField(choices=[('BOOKED', 'Запланирована'), ('CANCELLED', 'Запись отменена'), ('NO_SHOW', 'Неявка пациента'), ('COMPLETED', 'Завершен')], db_column='status', default='BOOKED', max_length=20)),
                ('complains', models.TextField(db_column='complains')),
                ('disease_id', models.ForeignKey(blank=True, db_column='disease_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_server_app.disease')),
                ('doctor_id', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='hospital_server_app.doctor')),
                ('patient_id', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='hospital_server_app.patient')),
                ('pres_id', models.ForeignKey(blank=True, db_column='pres_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_server_app.prescription')),
            ],
            options={
                'db_table': 'reception_log',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('schedule_id', models.AutoField(db_column='schedule_id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='schedule_date')),
                ('start_time', models.TimeField(db_column='start_time')),
                ('end_time', models.TimeField(db_column='end_time')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='hospital_server_app.doctor')),
            ],
            options={
                'db_table': 'schedule',
                'ordering': ['date', 'start_time'],
                'unique_together': {('doctor', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(db_column='dosage', help_text="Например: '500 мг 3 раза в день после еды, 7 дней'", max_length=100)),
                ('drug_id', models.ForeignKey(db_column='drug_id', on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_in', to='hospital_server_app.drug')),
                ('pres_id', models.ForeignKey(db_column='pres_id', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_drugs', to='hospital_server_app.prescription')),
            ],
            options={
                'db_table': 'pres_composition',
                'unique_together': {('pres_id', 'drug_id')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('slot_id', models.AutoField(db_column='slot_id', primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(db_column='start_datetime')),
                ('end_datetime', models.DateTimeField(db_column='end_datetime')),
                ('is_booked', models.BooleanField(db_column='is_booked', default=False)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='hospital_server_app.doctor')),
            ],
            options={
                'db_table': 'time_slot',
                'ordering': ['start_datetime'],
                'unique_together': {('doctor', 'start_datetime')},
            },
        ),
    ]
