# Generated by Django 6.1.1 on 2026-10-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_server_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorschedule',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor_id', 'date')},
        ),
    ]
